let jokes = [
  { id: 1, joke: "Why don't scientists trust atoms? Because they make up everything." },
  { id: 2, joke: "Why did the scarecrow win an award? Because he was outstanding in his field." },
  { id: 3, joke: "I told my wife she was drawing her eyebrows too high. She looked surprised." },
  { id: 4, joke: "I'm reading a book about anti-gravity. It's impossible to put down." },
  { id: 5, joke: "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them." },
  { id: 6, joke: "Why can't you give Elsa a balloon? Because she'll let it go." },
  { id: 7, joke: "I used to hate facial hair, but then it grew on me." },
  { id: 8, joke: "Why did the bicycle fall over? Because it was two-tired." },
  { id: 9, joke: "What do you call cheese that isn't yours? Nacho cheese." },
  { id: 10, joke: "I would tell you a construction joke, but I'm still working on it." },
  { id: 11, joke: "Why do cows wear bells? Because their horns don't work." },
  { id: 12, joke: "What do you call a fake noodle? An impasta." },
  { id: 13, joke: "I stayed up all night wondering where the sun went. Then it dawned on me." },
  { id: 14, joke: "Why did the coffee file a police report? It got mugged." },
  { id: 15, joke: "What do you call a sleeping dinosaur? A dino-snore." },
  { id: 16, joke: "I'm on a seafood diet. I see food and I eat it." },
  { id: 17, joke: "Why don't eggs tell jokes? They'd crack each other up." },
  { id: 18, joke: "What do you call a bear with no teeth? A gummy bear." },
  { id: 19, joke: "Why did the scarecrow become a successful therapist? He was great at listening in the field." },
  { id: 20, joke: "Did I tell you the joke about paper? Never mind, it's tearable." },
  { id: 21, joke: "Why can't a nose be 12 inches long? Because then it would be a foot." },
  { id: 22, joke: "What do you call a lazy kangaroo? A pouch potato." },
  { id: 23, joke: "I told my doctor I broke my arm in two places. He told me to stop going to those places." },
  { id: 24, joke: "Why did the golfer bring an extra pair of pants? In case he got a hole in one." },
  { id: 25, joke: "What's a vampire's favourite fruit? A blood orange." },
  { id: 26, joke: "Why did the tomato turn red? Because it saw the salad dressing." },
  { id: 27, joke: "I asked the librarian if they had books about paranoia. She whispered, 'They're right behind you.'" },
  { id: 28, joke: "What do you call a fish without eyes? A fsh." },
  { id: 29, joke: "Why don't skeletons fight each other? They don't have the guts." },
  { id: 30, joke: "I used to be a banker, but I lost interest." },
  { id: 31, joke: "What do you call an alligator in a vest? An investigator." },
  { id: 32, joke: "Why did the math book look so sad? Because it had too many problems." },
  { id: 33, joke: "What do you call a snowman with a six-pack? An abdominal snowman." },
  { id: 34, joke: "I'm writing a book on reverse psychology. Please don't buy it." },
  { id: 35, joke: "Why did the stadium get hot after the game? All the fans left." },
  { id: 36, joke: "What do you call a cow on a trampoline? A milkshake." },
  { id: 37, joke: "I tried to come up with a joke about time travel, but you didn't like it." },
  { id: 38, joke: "Why do programmers prefer dark mode? Because light attracts bugs." },
  { id: 39, joke: "What do you call a programmer from Finland? Nerdic." },
  { id: 40, joke: "Why was the JavaScript developer sad? Because he didn't Node how to Express himself." },
  { id: 41, joke: "A SQL query walks into a bar, walks up to two tables and asks... 'Can I join you?'" },
  { id: 42, joke: "Why did the developer go broke? Because he used up all his cache." },
  { id: 43, joke: "What's a computer's favourite snack? Microchips." },
  { id: 44, joke: "Why do Java developers wear glasses? Because they don't C#." },
  { id: 45, joke: "I have a joke about an infinite loop. I have a joke about an infinite loop. I have a joke about..." },
  { id: 46, joke: "Why was the function sad? It had too many arguments." },
  { id: 47, joke: "What do you call a group of 8 hobbits? A hobbyte." },
  { id: 48, joke: "Why did the developer quit his job? Because he didn't get arrays." },
  { id: 49, joke: "How do you comfort a JavaScript bug? You console it." },
  { id: 50, joke: "Why did the React component break up with the state? It had too many changes to handle." },
    ]

export default jokes